import { HomeIcon, UserIcon, CogIcon } from '@heroicons/vue/24/outline';
export const navigationItems = [
    {
        name:'Dashboard',
        path:'/dashboard',
        icon:HomeIcon,
        panels:['Admin','Tenant']
    },
     {
        name:'Users',
        path:'/UsersList',
        icon:UserIcon,
        panels:['Admin','Tenant']
    },
     {
        name:'Medicines',
        path:'/medicines',
        icon:CogIcon,
        panels:['Tenant']
    },
    {
        name:'Medicines',
        path:'/medicines',
        icon:CogIcon,
        panels:['Tenant']
    },
    {
        name:'Medicines',
        path:'/medicines',
        icon:CogIcon,
        panels:['Tenant']
    },
    {
        name:'Medicines',
        path:'/medicines',
        icon:CogIcon,
        panels:['Tenant']
    },
    {
        name:'Medicines',
        path:'/medicines',
        icon:CogIcon,
        panels:['Tenant']
    },
    {
        name:'Medicines',
        path:'/medicines',
        icon:CogIcon,
        panels:['Tenant']
    },
    {
        name:'Medicines',
        path:'/medicines',
        icon:CogIcon,
        panels:['Tenant']
    },
    {
        name:'Medicines',
        path:'/medicines',
        icon:CogIcon,
        panels:['Tenant']
    }
]